/*
 * data_model.h
 *
 *  Created on: Jul 27, 2023
 *      Author: i.dymov
 */

#ifndef INC_DATA_MODEL_H_
#define INC_DATA_MODEL_H_
#define REGISTER_COUNT  REGISTER_LAST_ADR
#define LAMP_DATA_SIZE 5
#define DOOR_ADDR 0x01
#define REMOTE_ADDR 0x02
#define FIRE_ADDR 0x03
#define LOCAL_ADDR 0x04
#define REMOTE_ACT_ADDR 0x05
#define ERROR_LAMP_RE1_ADDR 0x06
#define ERROR_LAMP_RE2_ADDR 0x07
#define LAMP1   0x08
#define LAMP2   (LAMP1 + LAMP_DATA_SIZE)
#define LAMP3   (LAMP2 + LAMP_DATA_SIZE)
#define LAMP4   (LAMP3 + LAMP_DATA_SIZE)
#define LAMP5   (LAMP4 + LAMP_DATA_SIZE)
#define LAMP6   (LAMP5 + LAMP_DATA_SIZE)
#define LAMP7   (LAMP6 + LAMP_DATA_SIZE)
#define LAMP8   (LAMP7 + LAMP_DATA_SIZE)
#define LAMP9   (LAMP8 + LAMP_DATA_SIZE)
#define LAMP10   (LAMP9 + LAMP_DATA_SIZE)
#define LAMP11   (LAMP10 + LAMP_DATA_SIZE)
#define LAMP12   (LAMP11 + LAMP_DATA_SIZE)
#define LAMP13   (LAMP12 + LAMP_DATA_SIZE)
#define LAMP14   (LAMP13 + LAMP_DATA_SIZE)
#define LAMP15   (LAMP14 + LAMP_DATA_SIZE)
#define LAMP16   (LAMP15 + LAMP_DATA_SIZE)
#define LAMP17   (LAMP16 + LAMP_DATA_SIZE)
#define LAMP18   (LAMP17 + LAMP_DATA_SIZE)
#define LAMP19   (LAMP18 + LAMP_DATA_SIZE)
#define LAMP20   (LAMP19 + LAMP_DATA_SIZE)
#define LAMP21   (LAMP20 + LAMP_DATA_SIZE)
#define LAMP22   (LAMP21 + LAMP_DATA_SIZE)
#define LAMP23   (LAMP22 + LAMP_DATA_SIZE)
#define LAMP24   (LAMP23 + LAMP_DATA_SIZE)
#define LAMP25   (LAMP24 + LAMP_DATA_SIZE)
#define LAMP26   (LAMP25 + LAMP_DATA_SIZE)
#define LAMP27   (LAMP26 + LAMP_DATA_SIZE)
#define LAMP28   (LAMP27 + LAMP_DATA_SIZE)
#define LAMP29   (LAMP28 + LAMP_DATA_SIZE)
#define LAMP30   (LAMP29 + LAMP_DATA_SIZE)
#define LAMP31   (LAMP30 + LAMP_DATA_SIZE)
#define LAMP32   (LAMP31 + LAMP_DATA_SIZE)
#define LAMP33   (LAMP32 + LAMP_DATA_SIZE)
#define LAMP34   (LAMP33 + LAMP_DATA_SIZE)
#define LAMP35   (LAMP34 + LAMP_DATA_SIZE)
#define LAMP36   (LAMP35 + LAMP_DATA_SIZE)
#define LAMP37   (LAMP36 + LAMP_DATA_SIZE)
#define LAMP38   (LAMP37 + LAMP_DATA_SIZE)
#define LAMP39   (LAMP38 + LAMP_DATA_SIZE)
#define LAMP40   (LAMP39 + LAMP_DATA_SIZE)
#define LAMP41   (LAMP40 + LAMP_DATA_SIZE)
#define LAMP42   (LAMP41 + LAMP_DATA_SIZE)
#define LAMP43   (LAMP42 + LAMP_DATA_SIZE)
#define LAMP44   (LAMP43 + LAMP_DATA_SIZE)
#define REGISTER_LAST_ADR  (LAMP44 + LAMP_DATA_SIZE)

void SetData(uint16_t index, uint16_t data);
uint16_t GetData(uint16_t index);

#endif /* INC_DATA_MODEL_H_ */
